/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calccomplexe.h"


void calccompprog_1(char *host)
{
	CLIENT *clnt;
	complexe  *result_1;
	complexe  add_1_arg;
	complexe  *result_2;
	complexe  mul_1_arg;
	void  *result_3;
	complexe  init_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCCOMPPROG, CALCVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	init_1_arg.pentiere = 10;
	init_1_arg.pimaginaire = 02;
	
	add_1_arg = init_1_arg;
	
	result_3 = init_1(&init_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf ("init: %d.%f \n", init_1_arg.pentiere, init_1_arg.pimaginaire);
	
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	//printf ("add: %d.%f \n", *result_1.pentiere, *result_1.pimaginaire);
	
	result_2 = mul_1(&mul_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calccompprog_1 (host);
exit (0);
}
