/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calccomplexe.h"

static complexe current;

int *
add_1_svc(complexe *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	current.pentiere = current.pentiere + argp->pentiere;
	current.pimaginaire = current.pimaginaire + argp->pimaginaire;
        
        printf ("current add %d.%f \n", current.pentiere, current.pimaginaire);
        //result = current;
	return &result;
}

int *
mul_1_svc(complexe *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
init_1_svc(complexe *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
